#define LOG_LEVEL 2
#include "ctarget.h"
#define NUMBER_OF_FEDERATES 1
#define TARGET_FILES_DIRECTORY "/home/rsambouncer/lf/minimal/src-gen/HelloWorld"
#include "core/reactor.c"
// Code generated by the Lingua Franca compiler from:
// file://home/rsambouncer/lf/minimal/HelloWorld.lf
// =============== START reactor class HelloWorld2
typedef struct {
    int bank_index;
    bool success;
    reaction_t ___reaction_0;
    reaction_t ___reaction_1;
    trigger_t ___startup;
    reaction_t* ___startup_reactions[1];
    trigger_t ___shutdown;
    reaction_t* ___shutdown_reactions[1];
} helloworld2_self_t;
void helloworld2reaction_function_0(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    helloworld2_self_t* self = (helloworld2_self_t*)instance_args;
    
    #pragma GCC diagnostic pop
    printf("Hello World.\n");
    self->success = true;
        
}
void helloworld2reaction_function_1(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    helloworld2_self_t* self = (helloworld2_self_t*)instance_args;
    
    #pragma GCC diagnostic pop
    printf("Shutdown invoked.\n");
    if (!self->success) {
        fprintf(stderr, "ERROR: startup reaction not executed.\n");
        exit(1);
    }
        
}
helloworld2_self_t* new_HelloWorld2() {
    helloworld2_self_t* self = (helloworld2_self_t*)calloc(1, sizeof(helloworld2_self_t));
    self->___reaction_0.number = 0;
    self->___reaction_0.function = helloworld2reaction_function_0;
    self->___reaction_0.self = self;
    self->___reaction_0.deadline_violation_handler = NULL;
    self->___reaction_0.STP_handler = NULL;
    self->___reaction_0.name = "?";
    self->___reaction_1.number = 1;
    self->___reaction_1.function = helloworld2reaction_function_1;
    self->___reaction_1.self = self;
    self->___reaction_1.deadline_violation_handler = NULL;
    self->___reaction_1.STP_handler = NULL;
    self->___reaction_1.name = "?";
    self->___startup_reactions[0] = &self->___reaction_0;
    self->___startup.last = NULL;
    self->___startup.reactions = &self->___startup_reactions[0];
    self->___startup.number_of_reactions = 1;
    self->___startup.is_timer = false;
    self->___shutdown_reactions[0] = &self->___reaction_1;
    self->___shutdown.last = NULL;
    self->___shutdown.reactions = &self->___shutdown_reactions[0];
    self->___shutdown.number_of_reactions = 1;
    self->___shutdown.is_timer = false;
    return self;
}
void delete_HelloWorld2(helloworld2_self_t* self) {
    if (self->___reaction_0.output_produced != NULL) {
        free(self->___reaction_0.output_produced);
    }
    if (self->___reaction_0.triggers != NULL) {
        free(self->___reaction_0.triggers);
    }
    if (self->___reaction_0.triggered_sizes != NULL) {
        free(self->___reaction_0.triggered_sizes);
    }
    if (self->___reaction_1.output_produced != NULL) {
        free(self->___reaction_1.output_produced);
    }
    if (self->___reaction_1.triggers != NULL) {
        free(self->___reaction_1.triggers);
    }
    if (self->___reaction_1.triggered_sizes != NULL) {
        free(self->___reaction_1.triggered_sizes);
    }
    for(int i = 0; i < self->___reaction_0.num_outputs; i++) {
        free(self->___reaction_0.triggers[i]);
    }
    for(int i = 0; i < self->___reaction_1.num_outputs; i++) {
        free(self->___reaction_1.triggers[i]);
    }
    free(self);
}
// =============== END reactor class HelloWorld2

// =============== START reactor class HelloWorld
typedef struct {
    int bank_index;
} helloworld_self_t;
helloworld_self_t* new_HelloWorld() {
    helloworld_self_t* self = (helloworld_self_t*)calloc(1, sizeof(helloworld_self_t));
    return self;
}
void delete_HelloWorld(helloworld_self_t* self) {
    free(self);
}
// =============== END reactor class HelloWorld

void __set_default_command_line_options() {
}
// Array of pointers to timer triggers to be scheduled in __initialize_timers().
trigger_t** __timer_triggers = NULL;
int __timer_triggers_size = 0;
// Array of pointers to timer triggers to be scheduled in __trigger_startup_reactions().
reaction_t* __startup_reactions[1];
int __startup_reactions_size = 1;
// Array of pointers to shutdown triggers.
reaction_t* __shutdown_reactions[1];
int __shutdown_reactions_size = 1;
trigger_t* __action_for_port(int port_id) {
    return NULL;
}
void __initialize_trigger_objects() {
    
    // ************* Instance HelloWorld of class HelloWorld
    helloworld_self_t* helloworld_self = new_HelloWorld();
    //***** Start initializing HelloWorld
    // ************* Instance HelloWorld.a of class HelloWorld2
    helloworld2_self_t* helloworld_a_self = new_HelloWorld2();
    //***** Start initializing HelloWorld.a
    __startup_reactions[0] = &helloworld_a_self->___reaction_0;
    __shutdown_reactions[0] = &helloworld_a_self->___reaction_1;
    static bool helloworld_a_initial_success = false;
    helloworld_a_self->success = helloworld_a_initial_success;
    //***** End initializing HelloWorld.a
    //***** End initializing HelloWorld
    // Populate arrays of trigger pointers.
    helloworld_self->bank_index = 0;
    helloworld_a_self->bank_index = 0;
    // Total number of outputs produced by the reaction.
    helloworld_a_self->___reaction_0.num_outputs = 0;
    // Allocate arrays for triggering downstream reactions.
    if (helloworld_a_self->___reaction_0.num_outputs > 0) {
        helloworld_a_self->___reaction_0.output_produced 
                = (bool**)malloc(sizeof(bool*) * helloworld_a_self->___reaction_0.num_outputs);
        helloworld_a_self->___reaction_0.triggers 
                = (trigger_t***)malloc(sizeof(trigger_t**) * helloworld_a_self->___reaction_0.num_outputs);
        helloworld_a_self->___reaction_0.triggered_sizes 
                = (int*)malloc(sizeof(int) * helloworld_a_self->___reaction_0.num_outputs);
    }
    // Initialize the output_produced array.
    // Total number of outputs produced by the reaction.
    helloworld_a_self->___reaction_1.num_outputs = 0;
    // Allocate arrays for triggering downstream reactions.
    if (helloworld_a_self->___reaction_1.num_outputs > 0) {
        helloworld_a_self->___reaction_1.output_produced 
                = (bool**)malloc(sizeof(bool*) * helloworld_a_self->___reaction_1.num_outputs);
        helloworld_a_self->___reaction_1.triggers 
                = (trigger_t***)malloc(sizeof(trigger_t**) * helloworld_a_self->___reaction_1.num_outputs);
        helloworld_a_self->___reaction_1.triggered_sizes 
                = (int*)malloc(sizeof(int) * helloworld_a_self->___reaction_1.num_outputs);
    }
    // Initialize the output_produced array.
    // Reaction 0 of HelloWorld.a does not depend on one maximal upstream reaction.
    helloworld_a_self->___reaction_0.last_enabling_reaction = NULL;
    // Reaction 1 of HelloWorld.a depends on one maximal upstream reaction.
    helloworld_a_self->___reaction_1.last_enabling_reaction = &(helloworld_a_self->___reaction_0);
    // doDeferredInitialize
    // Connect inputs and outputs for reactor HelloWorld.
    // Connect inputs and outputs for reactor HelloWorld.a.
    // END Connect inputs and outputs for reactor HelloWorld.a.
    // END Connect inputs and outputs for reactor HelloWorld.
    
    helloworld_a_self->___reaction_0.chain_id = 1;
    // index is the OR of level 0 and 
    // deadline 140737488355327 shifted left 16 bits.
    helloworld_a_self->___reaction_0.index = 0x7fffffffffff0000LL;
    helloworld_a_self->___reaction_1.chain_id = 1;
    // index is the OR of level 1 and 
    // deadline 140737488355327 shifted left 16 bits.
    helloworld_a_self->___reaction_1.index = 0x7fffffffffff0001LL;
    calculate_epoch_offset();
}
void __trigger_startup_reactions() {
    
    for (int i = 0; i < __startup_reactions_size; i++) {
        if (__startup_reactions[i] != NULL) {
            _lf_enqueue_reaction(__startup_reactions[i]);
        }
    }
}
void __initialize_timers() {
}
void logical_tag_complete(tag_t tag_to_send) {
}
bool __trigger_shutdown_reactions() {                          
    for (int i = 0; i < __shutdown_reactions_size; i++) {
        if (__shutdown_reactions[i] != NULL) {
            _lf_enqueue_reaction(__shutdown_reactions[i]);
        }
    }
    // Return true if there are shutdown reactions.
    return (__shutdown_reactions_size > 0);
}
void terminate_execution() {}
